### ISSUE TITLE
MotifViewer

### ISSUE THREAD

**Issue by LiQingsolab** [tzina97/netMHCpan#16]
Hello sir,

    We used the MotifViewer function in NetMHCpan4.1, and found that HLA-B*15:18 has it‘s peptide Motif. But when we searched  HLA-B*15:18 in IEDB database, we can only find 5 positvie peptide result ! So,If it is convenient, I want to known the resouce you used to predict  the motif of HLA-B*15:18, Is there another source of data? or the data you generate yourself ? 

Looking forward to your reply! 
Blessings！

**Comment by richelbilderbeek** [comment]
Hi @LiQingsolab, 

The purpose of this repo is to call [NetMHCPan](https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1/) from R.

Answers to your questions are likely to be found at [the  NetMHCPan page](https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1/).

Good luck and cheers, Richel Bilderbeek
